### ISSUE TITLE
Error message: "Progress bar resource is corrupt! Please redownload with all files" (downloaded .zip, AND run file before with no problems)

### ISSUE THREAD

**Issue by drmstwizard** [hsw107/Photoshop-Export-Layers-to-Files-Fast#127]

**Comment by drmstwizard** [comment]
Yes, I am - here is a screenshot of the error message. Even when I redownload the full script/directory and then run it immediately after unzipping, this pops up. It did not used to have this issue (running from the same directory and path and everything.)

**Comment by hsw107** [comment]
Since I can't really see what'd going on I'm going to leave a kind of comprehensive guide to make sure no mistakes would happen along the way.

For reference, I'm currently using Photoshop CC 2019 (specifically release 20.0.1)
Here are [screenshots and a step-by-step tutorial](https://imgur.com/a/QjxctwT).

There are a few ways I know of this error could appear:
1) The script is run from the ZIP file, instead of the extracted folder
2) The script is run from a different directory than the dialog JSON file
3) The dialog JSON file has had its name changed
4) The dialog JSON file itself is missing or invalid

Since I was able to download and use this script successfully just now using the steps above, this eliminates number 4 as being the issue, so it may be 1 or 2, or 3, so I would check those.

Additionally here is the code that actually is run prior to the error being thrown:
```
    // read progress bar resource
    var rsrcFile = new File(env.scriptFileDirectory + "/" + encodeURI("Export Layers To Files (Fast)-progress_bar.json"));
    var rsrcString = loadResource(rsrcFile);
    if (!rsrcString) {
        return false;
    }

    // create window
    var win;
    try {
        win = new Window(rsrcString);
    } catch (e) {
        alert("Progress bar resource is corrupt! Please, redownload the script with all files.", "Error", true);
        return false;
    }
```

As you can see the only way this would fail is if it has trouble loading the resource itself.

**Comment by drmstwizard** [comment]
OK; I've loaded the script fresh and purged it from the Presets of my Photoshop CS6.0, but now this is the error message that pops up instead:

![Image1](https://user-images.githubusercontent.com/29028771/54489077-97b3e200-4876-11e9-8161-fbffd08ab8ea.png)

**Comment by hsw107** [comment]
Alright, so this is a bit difficult for me to test as I just have CC on my laptop now, not CS6.0
But, try opening the `progress_bar.json` file and find this part:
```        
bar: Progressbar {
            preferredSize: [300, 16]
        },
```
And change it to:
```
        bar: Progressbar {
            value: 0,
            preferredSize: [300, 16]
        },
```

Let me know if that helps at all.

Otherwise this may need to wait. I have an older version of Photoshop on my desktop, but I'll need to find some time to test there.
Ultimately, from my research though it sounds like CS6 just has some weird issues with scripts.
If you don't need some of the newer features of this script, you can always downgrade and download older versions of this script through the releases tab.

**Comment by drmstwizard** [comment]
Hmm, the previous release https://github.com/hsw107/Photoshop-Export-Layers-to-Files-Fast/commit/b313e785ea358e5184f13fc687ac3b0d4836842a throws the exact same error message, as did updating the progress-bars.json file with the suggested code.

**Comment by eleow** [comment]
Experiencing the same error message with Photoshop CS6 as well
